const BjBrokaccDetailModel  = function(options){
	//主键
	this["id"]="",
	//经纪费计提主键
	this["brokerageAccrueId"]="",
	//保单号
	this["policyNo"]="",
	//批单号
	this["ratifyPolicyNo"]="",
	//性质
	this["nature"]="",
	//所属批次
	this["belongsBatch"]="",
	//所属机构
	this["belongsOrgId"]="",
	//所属部门
	this["belongsDeptId"]="",
	//所属团队
	this["belongsTeamId"]="",
	//业务员/代理人
	this["salesman"]="",
	//出单保险公司
	this["insCompanyId"]="",
	//保险险类
	this["insKindId"]="",
	//保险产品
	this["insProductId"]="",
	//期数
	this["periods"]="",
	//保费（税前）（元）
	this["premiumPreTax"]="",
	//保费（税后）（元）
	this["premiumAfterTax"]="",
	//起保日期
	this["policyBegindate"]="",
	//终保日期
	this["policyEnddate"]="",
	//签单日期
	this["signDate"]="",
	//生成时间
	this["createtime"]="",
	//经纪费计提比例（%）
	this["brokerageAccureRatio"]="",
	//应收经纪费（税后）（元）
	this["receivBrokeragePretax"]="",
	//应收经纪费增值税（元）
	this["receivBrokerageVtax"]="",
	//应收经纪费（税前）（元）
	this["receivBrokerageAftertax"]="",
	//创建者所属机构
	this["pkOrg"]="",
	//创建者所属部门
	this["pkDept"]="",
	//修改者
	this["modifier"]="",
	//修改时间
	this["modified"]="",
	//创建者
	this["creator"]="",
	//创建时间
	this["created"]="",
	//租户id
	this["tenantId"]="",
	//自定义1
	this["def1"]="",
	//自定义2
	this["def2"]="",
	//自定义3
	this["def3"]="",
	//自定义4
	this["def4"]="",
	//自定义5
	this["def5"]="",
	//时间戳
	this["ts"]="",
	//删除标识
	this["dr"]=""
	if(options){
		for(var attr in options )
		this[attr] = options[attr]
	}
} 
export default BjBrokaccDetailModel